#!/bin/sh

set -e

source docker-partkeepr-install

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

mkdir -p /run/nginx
mkdir -p /run/nginx/sock
rm -vf /run/nginx/sock/http

nginx
crontab /etc/partkeepr.cron
mkdir -p "$APP_HOME/app/logs"
crond
exec "$@"
